### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [HendrikBK/ann-radcliffe_the-mysteries-of-udolpho#1]
- [ ] Make sure you update the toolset.

# Typography

- [ ] `typogrify` makes many changes which should be accepted.
- [ ] 89bcde50172de48b5f8793b5cd915a966190f5fb: This doesn’t look like the best change to me. It would be more readable if the quote ended in a comma, and the following “said *x*” remained in lowercase.
- [ ] Remove the `Chapter` labels from each chapter.
- [ ] The chapter 3 epigraph should be using elision.

# Semantics

- [ ] Instead of `<em>`s in `a <em xml:lang="fr">salle à manger</em>, a <em xml:lang="fr">salon</em>, a <em xml:lang="fr">salle au commune</em>`, just use `<i>`s.
- [ ] Remove the `span epub:type` elements around loanwords into English like `château` unless those loanwords are also part of proper names in the original language. (See [8.2.9.2](https://standardebooks.org/manual/1.7.4/8-typography#8.2.9.2).)
- [ ] Remove `<em>`s around `debonnaire`, and also modernize to `debonair` in a separate commit.
- [ ] You have many examples of `em epub:type` elements, as seen in commit 292420e818dfdaa8a95681eb8dfd32ca2e9022ae. There are two possibilities for these. If these are loanwords that are found in Merriam-Webster, and were originally italicized as foreign-language words, we should totally remove the semantics around them. If they are actually foreign-language words, that are not found in Merriam-Webster, they should be italicized in an `i` tag and not an `em`. That being said most of them looked like loanwords at first glance. Use `grep --recursive --line-number --extended-regexp "<i|<em" src/epub/text/*.xhtml` to help you examine all instances of your italics usage.
- [ ] `LAURENTINI DI UDOLPHO` should not be in all-caps. If you need an all-caps appearance, use CSS to apply `text-transform: lowercase` to the header. (This might seem a little counter-intuitive—why not uppercase? But the header rule already applies the small-caps font variant, so lowercase will make it all small caps, which looks closer to what the printed text is.)
- [ ] For `cite` elements that are referring to a book/play/etc., the title should get the appropriate italics and semantics. Make sure you get in the [epigraph CSS for italics in the citation](https://standardebooks.org/manual/1.7.4/7-high-level-structural-patterns#7.4.1) too.
- [ ] Whenever you quote a *part* (e.g. a stanza from *Macbeth*) of a poetic work, use `z3998:verse`. `z3998:poem` is for an entire quoted poem or poems in poetry collections.

# Spelling

- [ ] `modernize-spelling` makes some changes to prose which should be accepted.
- [ ] I think we should standardize the hyphenation of “fairyland” and “glowworm,” even though they originally appear in a verse context.

# Metadata

- [ ] IA link should be `https://archive.org/details/mysteriesudolph00unkngoog`. Same thing in the colophon and imprint.
- [ ] Capitalize *Northanger Abbey* in the long description. We should revise the third paragraph—let’s not use the second person perspective in a long description (no “you”). The last sentence is also very vague; can we be more specific about what works reference this? What is the significance of those references?
- [ ] Looks like you copied Jacob van Ruisdael’s name incorrectly. You are missing the `l`.
- [ ] Jacob van Ruisdael should have a full-name property (Jacob Isaackszoon van Ruisdael).

# Colophon

- [ ] Instead of `in c. 1650`, use `circa 1650`.

# Commit History

- [ ] You need to use `git rebase -i --root` to rebase the Gutenberg license out of `body.xhtml` in the initial commit. We are not supposed to commit the Gutenberg license into our code. Please let me know if you need more detailed instructions on rebasing.
- [ ] 9c4ca19596c547e4998cb8a304d11c6f8513626c: I don’t think this is an editorial commit. The changes seem supported by the original text.

**Comment by weijia-cheng** [comment]
I noticed some issues in your recent changes.

- [ ] 9e1306c81aecb2172f00c464ba185712e2284c1c: This commit has some changes we will want to revert. We don't want to modernize hyphenation in the verse quotations, except for making the hyphenation consistent. We only modernize hyphenation in prose, not verse.
- [ ] 440b18234e9c71c5142626181afcae8f09bfe160: This commit changed the capitalization of "monsieur" in several cases. I'm guessing this is a regex accident, and we need to revert the capitalization back to the original.

As for doing a rebase, I would begin by reading [this guide](https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d) and creating a local copy of your repository as a backup in case you make a mistake while rebasing. Rebasing is very powerful and has the potential to really screw up your commit history, so it's a good precaution.

You'll begin by running the command `git rebase -i --root`. This will open a temporary file with your git text editor (usually vim; see [this page](https://docs.github.com/en/get-started/getting-started-with-git/associating-text-editors-with-git) for instructions on how to switch to some popular GUI editors). The temporary file will look like this:

```
pick e007db6 Initial commit
pick b26edd5 Clean and renamed files of volume 1
pick c0f272b Clean and rename files of volume 2
pick bd0761b Clean and renamed files for volume 3
pick eeda1c6 Clean and renamed files of volume 4
pick d43b2cb Fix titles
pick e70ec76 Add cover
pick 5c3c638 Renamed chapters
pick 1c9394b Typogrify
pick 7cb7a9e Semanticate
```

etc. You will need to change the `pick` in the first line `pick e007db6 Initial commit` to `edit`. Also, you need to find the `pick 9c4ca19 [Editorial] Change capitalization of a word` line and change `pick` there to `reword`. Once you have made those changes, save and quit from the temporary file.

Once you're in this point, you'll see the message

```
Stopped at e007db6...  Initial commit
You can amend the commit now, with

  git commit --amend 

Once you are satisfied with your changes, run

  git rebase --continue
```

At this point, you can edit the body file, delete the license, then run `git add -A` and then `git rebase --continue`. Then, git will try to automatically apply the following commits in sequence, but there will be a merge conflict while applying the commit that deleted `body.xhtml`. It will complain with this message:

```
CONFLICT (modify/delete): src/epub/text/body.xhtml deleted in b26edd5 (Clean and renamed files of volume 1) and modified in HEAD.  Version HEAD of src/epub/text/body.xhtml left in tree.
error: could not apply b26edd5... Clean and renamed files of volume 1
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply b26edd5... Clean and renamed files of volume 1
```

Once you get to that point, use `git rm src/epub/text/body.xhtml` to delete the body.xhtml file again and use `git rebase --continue` afterwards. Then the following commits will be applied without any issues until you get to a screen where you get to change the message of the `[Editorial] Change capitalization of a word` commit. Just delete `[Editorial]` there, save the buffer, and afterwards all of the remaining commits will be applied.

After you've done all this and run `git status`, you will see a message like 

```
wcheng@pop-os:~/git/ann-radcliffe_the-mysteries-of-udolpho$ git status
On branch main
Your branch and 'origin/main' have diverged,
and have 95 and 95 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

That means that your local repository has different history than your remote git repository. You need to use `git push --force` to overwrite your remote repository with your local history. Once you are done with this, your git commit history will look as it should.

I basically did the rebase myself locally and reproduced my steps here, so I can assure you these instructions work :) But please let me know if anything is unclear or you get stuck on anything.

**Comment by weijia-cheng** [comment]
Some follow-up issues:

- [ ] 02fd786d8d14fa6921961f8b74e2e4f38f204dc8 should be rebased and marked as non-editorial. Reverting incorrect editorial changes is not itself editorial.
- [ ] Sorry, I don't think I was clear enough on what to do with the titles in `cite`s. Instead of `<cite epub:type="se:name.publication.play"><i>Macbeth</i></cite>`, it should be `<cite><i epub:type="se:name.publication.play">Macbeth</i></cite>` with the semantics going on the italics.
- [ ] I still see some examples of `em`s on loanwords: eclât (I think this should be modernized to éclat by the way), conversazione. `em` should be removed on these.
- [ ] There are also still instances of `em`s with `xml:lang`s that need to be changed to `i`s. Use the command `se xpath '//em[@xml:lang]' .` to find all of them.
- [ ] In the endnotes, you have `em` around `The Traveller` which is the name of a poem. This needs to be italics with the poem title semantics like we discussed with the titles in citations. Please review [8.2.11](https://standardebooks.org/manual/1.7.4/8-typography#8.2.11).
- [ ] There are some usages of `em` that look like loanwords and not actual emphases, which should be removed. Some examples I noticed on a quick scan are clematis and Jarl Please review again with `grep --recursive --line-number --extended-regexp "<i|<em" src/epub/text/*.xhtml` and consider if any more `em`s should be removed--please feel free to ask in the mailing list if you find any unclear cases.
